CREATE OR REPLACE TRIGGER trg_salary_check
BEFORE INSERT OR UPDATE ON EMP
FOR EACH ROW
BEGIN
    IF :NEW.BasicSal > 50000 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Salary cannot exceed 50000');
    END IF;
END;
/